Repository Spring-Cooler/SGMA_Frontend, pull requests merged in 2024-09, with the labels that each got.

#15 Add: common css, App.vue, Navigation.vue, SideBar.vue
  index.html
  src/App.vue
  src/assets/logo.svg
  src/assets/style/common.css
  src/assets/style/main.css
  src/components/Navigation.vue
  src/components/SideBar.vue
  src/components/SideBarMenu.vue
  src/main.js
Labels: enhancement

#20 Refactor: 폴더 구조 변경 및 스케쥴 페이지
  src/App.vue
  src/assets/styles/color.css
  src/assets/styles/common.css
  src/components/layouts/Navigation.vue
  src/components/layouts/SideBar.vue
  src/components/layouts/SideBarMenu.vue
  src/main.js
  src/views/Schedule/SchedulePage.vue
  src/views/Schedule/components/StudyCalendar.vue
Labels: enhancement

#24 Feat: 홈 UI
  index.html
  src/App.vue
  src/api/users.js
  src/assets/images/graph-and-people_svgrepo.com.png
  src/assets/images/공지사항 변경 버튼.png
  src/assets/images/안내사항.png
  src/assets/styles/color.css
  src/components/common/YesNoButton.vue
  src/components/layouts/Navigation.vue
  src/components/layouts/SideBar.vue
  src/router/router.js
  src/views/user/components/NoticeBanner.vue
  src/views/user/page/Home.vue
Labels: enhancement

#26 Feat: 마이페이지 라우팅 설정
  package-lock.json
  package.json
  src/App.vue
  src/components/layouts/SideBar.vue
  src/components/layouts/SideBarMenu.vue
  src/main.js
  src/router/router.js
  src/views/user/components/NoticeBanner.vue
  src/views/user/page/Home.vue
  src/views/user/page/MyPage.vue
Labels: enhancement

#28 Feat: 로그인 모달창 추가
  src/App.vue
  src/assets/images/btn_kakao.png
  src/assets/images/btn_login.png
  src/assets/images/btn_naver.png
  src/components/common/LoginModal.vue
  src/components/layouts/Navigation.vue
  src/views/user/components/NoticeBanner.vue
  src/views/user/page/MyPage.vue
Labels: enhancement

#31 회원가입창
  src/components/common/LoginModal.vue
  src/components/common/YesNoButton.vue
  src/components/layouts/Navigation.vue
  src/views/user/components/RegisterModal.vue
  src/views/user/page/Home.vue
  src/views/user/page/MyPage.vue
Labels: enhancement

#32 Fix: 홈 화면 짤리는 오류 수정
  package-lock.json
  package.json
  src/App.vue
Labels: bug, enhancement

#33 Feat: 스터디그룹 내 사이드메뉴바 구현
  src/assets/styles/common.css
  src/components/layouts/GroupSideBar.vue
  src/router/router.js
  src/views/Group/page/StudyNoticePage.vue
Labels: enhancement

#36 Fix: main-content 너비 수정
  src/assets/styles/common.css
  src/components/common/SmallButton.vue
  src/views/Group/page/StudyNoticePage.vue
Labels: enhancement

#37 Feature/recruitment
  src/App.vue
  src/assets/styles/common.css
  src/views/Recruitment/EveryBoard.vue
  src/views/Recruitment/SingleBoard.vue
  src/views/Recruitment/components/List.vue
Labels: enhancement

#38 회원가입 이름, 이메일 입력 모달창
  src/components/common/LoginModal.vue
  src/components/layouts/SideBarMenu.vue
  src/views/user/components/RegisterModal.vue
Labels: enhancement

#39 Feat: 스터디 그룹 내 메뉴 초기 구현
  src/assets/styles/common.css
  src/components/common/Title.vue
  src/router/router.js
  src/views/Group/components/SearchBar.vue
  src/views/Group/page/StudyBoardPage.vue
  src/views/Group/page/StudyMemberPage.vue
  src/views/Group/page/StudyNoticePage.vue
  src/views/Group/page/StudyRecruitmentPage.vue
Labels: enhancement

#40 Feat, Fix: 스터디 그룹원 컴포넌트 생성 및 스크롤 오류 수정
  src/assets/images/default_profile.svg
  src/components/common/MediumButton.vue
  src/router/router.js
  src/views/Group/components/Member.vue
  src/views/Group/page/StudyBoardPage.vue
  src/views/Group/page/StudyMemberPage.vue
  src/views/Group/page/StudyNoticePage.vue
Labels: bug, enhancement

#45 Feat: 스터디 그룹원 관리 초기 세팅
  src/assets/styles/color.css
  src/assets/styles/common.css
  src/components/common/TinyButton.vue
  src/components/layouts/SideBarMenu.vue
  src/views/Group/components/Member.vue
  src/views/Group/components/SearchBar.vue
Labels: enhancement

#49 회원가입 모달창 step2
  src/assets/images/arrow_right.png
  src/assets/images/checkbox_checked.png
  src/assets/images/eye_closed.png
  src/assets/images/eye_open.png
  src/assets/styles/common.css
  src/components/common/LoginModal.vue
  src/components/layouts/Navigation.vue
  src/views/user/components/CodeSentModal.vue
  src/views/user/components/NoticeBanner.vue
  src/views/user/components/PrivacyPolicyModal.vue
  src/views/user/components/SignupStep1.vue
  src/views/user/components/SignupStep2.vue
  src/views/user/components/SignupStep3.vue
  src/views/user/page/MyPage.vue
Labels: enhancement

#47 Feat: 스터디그룹 자유게시판 검색 기능 구현
  src/components/common/Pagination.vue
  src/views/Group/components/SearchBar.vue
  src/views/Group/page/StudyBoardPage.vue
  vite.config.js
Labels: enhancement

#54 Feature/recruitment
  src/App.vue
  src/components/common/DeleteModal.vue
  src/router/router.js
  src/views/Recruitment/CreateGroup.vue
  src/views/Recruitment/FindStudyGroup.vue
  src/views/Recruitment/List.vue
  src/views/Recruitment/RecruitBoard.vue
  src/views/Recruitment/SingleBoard.vue
Labels: enhancement

#55 회원가입 모달창 UI 설계
  src/App.vue
  src/components/common/LoginModal.vue
  src/views/user/components/SignupStep1.vue
  src/views/user/components/SignupStep2.vue
  src/views/user/components/SignupStep3.vue
  vite.config.js
Labels: enhancement

#59 Refactor: 모달창 외부 클릭시 닫기 기능 제거
  src/App.vue
  src/components/common/LoginModal.vue
  src/views/user/components/SignupStep1.vue
  src/views/user/components/SignupStep2.vue
  src/views/user/components/SignupStep3.vue
Labels: enhancement

#58 Feat: 스터디 그룹원 추방 기능 구현
  src/components/common/DeleteModal.vue
  src/components/layouts/SideBarMenu.vue
  src/views/Group/components/Member.vue
  src/views/Group/page/StudyMemberManagePage.vue
Labels: enhancement

#61 Feat: 스터디 그룹 만들기 #60
  src/App.vue
  src/components/layouts/BoardTemplate.vue
  src/views/Group/components/DeleteModal.vue
  src/views/Recruitment/CreateGroup.vue
  src/views/Recruitment/components/DeleteModal.vue
Labels: enhancement

#62 로그인1 차Ui설계 및 사이드바 메뉴 에러 수정
  src/App.vue
  src/components/common/LoginModal.vue
  src/components/layouts/SideBarMenu.vue
  src/views/user/components/PrivacyPolicyModal.vue
  src/views/user/components/SignupStep1.vue
  src/views/user/components/SignupStep2.vue
  src/views/user/components/SignupStep3.vue
  src/views/user/page/MyPage.vue
Labels: bug

#66 Fix: 페이지네이션 disabled 버그 수정
  src/components/common/Pagination.vue
  src/components/layouts/PostHeader.vue
  src/router/router.js
  src/views/Group/components/Notice.vue
  src/views/Group/page/StudyBoardPage.vue
  src/views/Group/page/StudyNoticeDetailPage.vue
  src/views/Group/page/StudyNoticePage.vue
Labels: bug, enhancement

#67 Refactor: PostBody CSS 수정
  src/components/common/Pagination.vue
  src/components/common/PostContent.vue
  src/components/layouts/PostBody.vue
Labels: enhancement

#69 Navigation 에러 수정
  src/components/common/LoginModal.vue
  src/components/layouts/Navigation.vue
  src/views/user/components/SignupStep1.vue
Labels: bug, enhancement

#70 Refactor: 상단 내비 사용자 프로필 css 수정
  src/components/layouts/Navigation.vue
Labels: enhancement

#68 Feat: 게시글 댓글 작성, 삭제 기능 구현
  src/components/common/Comment.vue
  src/components/common/CommentInfo.vue
  src/components/common/CommentInput.vue
  src/components/layouts/CommentBody.vue
  src/components/layouts/CommentHeader.vue
  src/components/layouts/PostBody.vue
  src/components/layouts/PostFooter.vue
  src/components/layouts/PostHeader.vue
  src/components/layouts/PostTemplate.vue
  src/router/router.js
  src/views/Group/page/StudyBoardDetailPage.vue
  src/views/Group/page/StudyNoticeDetailPage.vue
  vite.config.js
Labels: enhancement

#71 Refactor: 상단내비에 로고 클릭시 홈화면 이동 기능 수정
  src/components/common/LoginModal.vue
  src/components/layouts/Navigation.vue
  src/views/user/components/SignupStep1.vue
  src/views/user/styles/user-common.css
Labels: enhancement

#72 Feat: 게시글 대댓글 기능 구현
  src/components/common/Comment.vue
  src/components/common/CommentInput.vue
  src/components/common/Reply.vue
  src/components/layouts/CommentHeader.vue
  src/components/layouts/PostTemplate.vue
  src/components/layouts/ReplyBody.vue
  src/views/Group/page/StudyBoardDetailPage.vue
  src/views/Group/page/StudyMemberManagePage.vue
  src/views/Group/page/StudyMemberPage.vue
  vite.config.js
Labels: enhancement

#73 Fix: Get을 통한 사용자 정보 조회시 param형식으로 수정
  src/App.vue
  src/api/user.js
  src/api/users.js
  src/components/common/LoginModal.vue
  src/components/layouts/Navigation.vue
  src/views/user/components/UserComments.vue
  src/views/user/components/UserProfile.vue
  src/views/user/page/MyPage.vue
Labels: enhancement

#78 Refactor: 모집글 개별 조회 페이지 및 신청
  src/views/Recruitment/SingleBoard.vue
Labels: enhancement

#77 Feat: 그룹내 게시글 수정 기능 구현
  package-lock.json
  package.json
  src/components/common/CommentInput.vue
  src/components/layouts/PostHeader.vue
  src/main.js
  src/router/router.js
  src/store.js
  src/views/Group/components/SearchBar.vue
  src/views/Group/page/StudyBoardDetailPage.vue
  src/views/Group/page/StudyBoardPage.vue
  src/views/Group/page/StudyNoticeDetailPage.vue
  src/views/Group/page/StudyNoticePage.vue
  src/views/Group/page/StudyPostModifyPage.vue
  src/views/Group/page/StudyPostUploadPage.vue
Labels: enhancement

#80 회원가입 Step1 기능 구현
  src/api/user.js
  src/views/user/components/SignupStep1.vue
  src/views/user/components/UserComments.vue
Labels: enhancement

#79 Fix: 게시글 작성 후 목록을 누르면 작성 페이지로 돌아가던 버그 수정
  src/components/common/Comment.vue
  src/components/common/CommentInput.vue
  src/components/common/Reply.vue
  src/components/layouts/CommentHeader.vue
  src/components/layouts/PostHeader.vue
  src/views/Group/page/StudyBoardDetailPage.vue
  src/views/Group/page/StudyBoardPage.vue
  src/views/Group/page/StudyMemberManagePage.vue
  src/views/Group/page/StudyMemberPage.vue
  src/views/Group/page/StudyNoticeDetailPage.vue
  src/views/Group/page/StudyNoticePage.vue
  src/views/Group/page/StudyPostModifyPage.vue
  src/views/Group/page/StudyPostUploadPage.vue
  vite.config.js
Labels: bug, enhancement

#82 Feat: 회원 탈퇴하기 기능 추가
  src/views/user/components/AccountDeactivationModal.vue
  src/views/user/components/UserProfile.vue
  src/views/user/page/MyPage.vue
Labels: enhancement

#84 Feat: 게시글 내용 줄바꿈 구현
  src/components/layouts/PostBody.vue
Labels: enhancement

#86 Feat: 비활성화 회원 재활성화 기능 추가
  src/api/user.js
  src/components/common/LoginModal.vue
  src/components/layouts/Navigation.vue
  src/views/user/components/AccountReactivationModal.vue
  src/views/user/components/FindId.vue
  src/views/user/components/SignupStep2.vue
Labels: enhancement

#87 스터디 그룹찾기(전체 조회)
  src/views/Recruitment/FindStudyGroup.vue
  vite.config.js
Labels: enhancement

#88 Refactor: 스터디그룹 코드 리팩토링
  src/components/layouts/CommentHeader.vue
  src/views/Group/components/Member.vue
  src/views/Group/components/Recruitment.vue
  src/views/Group/page/StudyBoardDetailPage.vue
  src/views/Group/page/StudyBoardPage.vue
  src/views/Group/page/StudyMemberManagePage.vue
  src/views/Group/page/StudyMemberPage.vue
  src/views/Group/page/StudyNoticeDetailPage.vue
  src/views/Group/page/StudyNoticePage.vue
  src/views/Group/page/StudyPostModifyPage.vue
  src/views/Group/page/StudyPostUploadPage.vue
  src/views/Group/page/StudyRecruitmentPage.vue
Labels: enhancement

#90 Feature/recruitment
  package-lock.json
  src/router/router.js
  src/views/Recruitment/FindStudyGroup.vue
  src/views/Recruitment/SingleBoard.vue
  vite.config.js
Labels: enhancement

#92 Feat: 비밀번호 재설정 기능 추가
  src/components/common/LoginModal.vue
  src/components/layouts/Navigation.vue
  src/views/user/components/AccountReactivationModal.vue
  src/views/user/components/ChangePasswordModal.vue
  src/views/user/components/PasswordResetStep1.vue
  src/views/user/components/PasswordResetStep2.vue
  src/views/user/components/UserProfile.vue
  src/views/user/page/MyPage.vue
Labels: enhancement

#93 Feat: 스터디 그룹 만들기 구현
  src/router/router.js
  src/store.js
  src/views/Group/page/CreateGroupPage.vue
  src/views/Group/page/StudyPostUploadPage.vue
  src/views/Recruitment/CreateGroup.vue
Labels: enhancement

#95 Feat: 아이디 찾기 기능 추가
  src/components/common/LoginModal.vue
  src/components/layouts/Navigation.vue
  src/views/user/components/FindIdStep1.vue
  src/views/user/components/FindIdStep2.vue
Labels: enhancement

#96 Feat: 스터디 그룹 찾기 기능 구현
  src/views/Recruitment/FindStudyGroup.vue
  src/views/Recruitment/components/SearchBar.vue
Labels: enhancement

#97 Feature/recruitment
  src/App.vue
  src/views/Recruitment/Applicant.vue
  vite.config.js
Labels: enhancement

#98 Feat: 내가 가입한 스터디그룹 가기
  src/assets/styles/common.css
  src/components/layouts/GroupSideBar.vue
  src/components/layouts/Navigation.vue
  src/components/layouts/PostHeader.vue
  src/components/layouts/SideBar.vue
  src/router/router.js
  src/views/Group/components/Board.vue
  src/views/Group/components/DeleteModal.vue
  src/views/Group/components/Member.vue
  src/views/Group/components/Notice.vue
  src/views/Group/page/CreateGroupPage.vue
  src/views/Group/page/StudyBoardDetailPage.vue
  src/views/Group/page/StudyBoardPage.vue
  src/views/Group/page/StudyMemberManagePage.vue
  src/views/Group/page/StudyNoticePage.vue
  src/views/Group/page/StudyRecruitmentPage.vue
  src/views/user/components/Group.vue
  src/views/user/components/UserProfile.vue
  src/views/user/page/MyPage.vue
  src/views/user/page/MyStudyGroupsPage.vue
Labels: enhancement

#99 Feat: 좋아요 구현
  package-lock.json
  src/components/layouts/PostHeader.vue
  src/views/Group/page/StudyBoardDetailPage.vue
  src/views/Recruitment/FindStudyGroup.vue
  src/views/user/page/MyStudyGroupsPage.vue
Labels: enhancement

#100 Fix: 레이아웃 수정
  src/assets/styles/common.css
  src/views/Group/components/Recruitment.vue
  src/views/Recruitment/FindStudyGroup.vue
Labels: enhancement

#102 Fix: 스터디 그룹찾기 메뉴바 이동 오류 수정
  src/views/Recruitment/FindStudyGroup.vue
Labels: bug, enhancement

#104 Fix: 하드코딩 수정
  src/components/layouts/GroupSideBar.vue
  src/components/layouts/SideBar.vue
  src/router/router.js
  src/views/Group/page/StudyRecruitmentPage.vue
  src/views/Recruitment/FindStudyGroup.vue
  src/views/Recruitment/RecruitmentDetailPage.vue
  src/views/Recruitment/SingleBoard.vue
  src/views/Recruitment/components/Recruitment.vue
Labels: enhancement

#107 Feat: 모집글 url 매핑
  src/components/layouts/PostHeader.vue
  src/components/layouts/SideBar.vue
  src/router/router.js
  src/views/Group/page/StudyBoardDetailPage.vue
  src/views/Group/page/StudyNoticeDetailPage.vue
  src/views/Group/page/StudyPostUploadPage.vue
  src/views/Group/page/StudyRecruitmentPage.vue
  src/views/Recruitment/FindStudyGroup.vue
  src/views/Recruitment/RecruitmentDetailPage.vue
  src/views/Recruitment/components/Recruitment.vue
Labels: enhancement

#108 카카오 로그인
  src/components/common/LoginModal.vue
  src/router/router.js
  src/views/user/components/FindIdStep1.vue
  src/views/user/components/KakaoCallback.vue
  src/views/user/components/ProfileOAuthModal.vue
Labels: enhancement

#110 네이버 로그인 기능 추가
  src/components/common/LoginModal.vue
  src/router/router.js
  src/views/user/components/KakaoCallback.vue
  src/views/user/components/NaverCallback.vue
  src/views/user/components/ProfileOAuthModal.vue
Labels: enhancement

#113 Feat: 스터디그룹 참가 신청 구현
  src/router/router.js
  src/views/Group/page/StudyPostModifyPage.vue
  src/views/Group/page/StudyPostUploadPage.vue
  src/views/Recruitment/FindStudyGroup.vue
  src/views/Recruitment/RecruitmentDetailPage.vue
Labels: enhancement
